M48
; DRILL file {KiCad 7.0.11} date Tue Mar  5 22:51:25 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-05T22:51:25-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0276
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0295
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0354
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.0394
%
G90
G05
T1
X6.05Y-3.675
X6.25Y-3.675
T2
X6.4Y-3.7
X6.4Y-3.75
X6.4Y-3.8
T3
X6.0998Y-3.5
X6.1998Y-3.5
T4
X6.4Y-3.3
X6.4Y-3.4
X6.4Y-3.5
X6.6Y-3.3
X6.6Y-3.4
X6.6Y-3.5
X6.6Y-3.8
X6.7Y-3.8
X6.8Y-3.3
X6.8Y-3.4
X6.8Y-3.5
X6.8Y-3.8
X6.9Y-3.8
X7.0Y-3.3
X7.0Y-3.4
X7.0Y-3.5
X7.0Y-3.8
X7.1Y-3.8
X7.2Y-3.3
X7.2Y-3.4
X7.2Y-3.5
X7.2Y-3.8
X7.3Y-3.8
X7.4Y-3.3
X7.4Y-3.4
X7.4Y-3.5
X7.4Y-3.8
M30
